export const GET_SALONS_SUCCESS = "GET_SALONS_SUCCESS";
export const GET_SALONS_PENDING = "GET_SALONS_PENDING";
export const GET_SALONS_ERROR = "GET_SALONS_ERROR";

export const DELETE_SALON_SUCCESS = "DELETE_SALON_SUCCESS";
export const DELETE_SALON_PENDING = "DELETE_SALON_PENDING";
export const DELETE_SALON_ERROR = "DELETE_SALON_ERROR";

export const ADD_SALON_SUCCESS = "ADD_SALON_SUCCESS";
export const ADD_SALON_PENDING = "ADD_SALON_PENDING";
export const ADD_SALON_ERROR = "ADD_SALON_ERROR";

export const EDIT_SALON_SUCCESS = "EDIT_SALON_SUCCESS";
export const EDIT_SALON_PENDING = "EDIT_SALON_PENDING";
export const EDIT_SALON_ERROR = "EDIT_SALON_ERROR";

export const ADD_SALON_TO_USER_SUCCESS = "ADD_SALON_TO_USER_SUCCESS";
export const ADD_SALON_TO_USER_PENDING = "ADD_SALON_TO_USER_PENDING";
export const ADD_SALON_TO_USER_ERROR = "ADD_SALON_TO_USER_ERROR";

export const DELETE_SALON_FROM_USER_SUCCESS = "DELETE_SALON_FROM_USER_SUCCESS";
export const DELETE_SALON_FROM_USER_PENDING = "DELETE_SALON_FROM_USER_PENDING";
export const DELETE_SALON_FROM_USER_ERROR = "DELETE_SALON_FROM_USER_ERROR";
